--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::SassExtensions::Functions::Configuration#add_configuration
is_singleton: false
name: add_configuration
params: (options)
visibility: public
