--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Compass::Configuration
includes: []

instance_methods: []

name: Configuration
superclass: 
