--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Set the current Rake application object.
full_name: Rake::application=
is_singleton: true
name: application=
params: (app)
visibility: public
