--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Current Rake Application
full_name: Rake::application
is_singleton: true
name: application
params: ()
visibility: public
