--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: "@configuration"
comment: 
- !ruby/struct:SM::Flow::P 
  body: The Compass configuration singleton.
full_name: Compass::configuration
is_singleton: true
name: configuration
params: () {|@configuration| ...}
visibility: public
