--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@return [Boolean] Whether outputs obsolete entries or not."
full_name: GetText::Tools::MsgCat::Config#output_obsolete_entries?
is_singleton: false
name: output_obsolete_entries?
params: ()
visibility: public
