--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@return [Boolean] Whether reports warning messages or not."
full_name: GetText::Tools::MsgCat::Config#report_warning?
is_singleton: false
name: report_warning?
params: ()
visibility: public
