--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@return [Array] Get array of values from Struct fields."
full_name: FFI::Struct#values
is_singleton: false
name: values
params: ()
visibility: public
