--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: update mode options
  name: backup
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: definition_po
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: "(#see #enable_fuzzy_matching?)"
  name: enable_fuzzy_matching
  rw: W
- !ruby/object:RI::Attribute 
  comment: 
  name: order
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: output
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: "(#see #output_obsolete_entries?)"
  name: output_obsolete_entries
  rw: W
- !ruby/object:RI::Attribute 
  comment: 
  name: po_format_options
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: reference_pot
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: update mode options
  name: suffix
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: update
  rw: RW
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@private"
constants: []

full_name: GetText::Tools::MsgMerge::Config
includes: 
- !ruby/object:RI::IncludedModule 
  name: GetText
instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: enable_fuzzy_matching?
- !ruby/object:RI::MethodSummary 
  name: output_obsolete_entries?
- !ruby/object:RI::MethodSummary 
  name: parse
name: Config
superclass: Object
